name : Github Action leanring
run-name : ${{ github.actor }} apprentissage de Github Action
on : [push]
jobs:
  Github-action-learning:
    runs-on: ubuntu-latest
    steps:
      - name: Step nommée
        run: echo "It's alive! ALIIIIIVE!"

      - run: echo "Le job a été déclenché par ${{ github.event_name }}"
      - run: echo "Ce job tourne sur ${{ runner.os }} ${{ runner.os }} ${{ runner.os }} "
      - run: echo "La branche est ${{ github.ref }} sur le dépôt ${{ github.repository }}"
